feat(config): new config redirectAllowList
americanexpress/one-app pull request #1051
Opened 2023-07-11 20:03 UTC by Matthew-Mallimo

## Description

This adds a new `appConfig` option to configure an allow list for redirects.

## Motivation and Context

We dont want to redirect anyone to malicious URLs in the case of user-inputed redirects.

## How Has This Been Tested?

Unit and locally

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

Allows further security enhancements through a customizable allow list.

2023-07-12 19:41 UTC, bishnubista commented on __tests__/server/middleware/checkStateForRedirect.spec.js
> +    expect(next).toHaveBeenCalled();
Shouldn't we clear mocks or add `toHaveBeenCalledTimes`?

2023-07-12 19:48 UTC, bishnubista submitted a review, later dismissed

2023-07-13 13:07 UTC, dogpatch626 submitted a review, later dismissed

2023-07-13 17:14 UTC, 10xLaCroixDrinker requested changes
It looks right now like the only way to revert the enabling this feature is to deploy a new module release that sets the value to `[]`. Please refactor so that the change can be rolled back to where this feature is not configured and will be disabled.

2023-07-17 17:07 UTC, Matthew-Mallimo commented on src/server/middleware/createRequestHtmlFragment.jsx
> +          if (!validateRedirectUrl(redirect.url)) {
Changed in 1f920a4e30ee9fa88371d9a2516f1348fa31d30b

2023-07-17 17:07 UTC, Matthew-Mallimo commented
> It looks right now like the only way to revert the enabling this feature is to deploy a new module release that sets the value to `[]`. Please refactor so that the change can be rolled back to where this feature is not configured and will be disabled.

Addressed in 1f920a4e30ee9fa88371d9a2516f1348fa31d30b

2023-07-17 18:39 UTC, bishnubista approved these changes

2023-07-27 13:45 UTC, 10xLaCroixDrinker approved these changes

2023-08-01 16:16 UTC, JAdshead commented on src/server/utils/onModuleLoad.js
> +    setRedirectAllowList(redirectAllowList);
what happens when a root module has a redirect allow list, then a new version gets released without a redirect allow list? this needs to ensure that its reset

2023-08-01 17:03 UTC, JAdshead commented on src/server/utils/redirectAllowList.js
> +  return false;
```suggestion
  // If a redirect list is not configured, allow the redirect.
  // This prevents the redirect allow list from becoming a breaking change.
  return redirectAllowList.length === 0 || isAllowedUrl(url)
```

2023-08-01 17:04 UTC, JAdshead commented on __tests__/server/utils/onModuleLoad.spec.jsx
> +  it('calls setStateConfig if setRedirectAllowList is supplied', () => {
```suggestion
  it('calls setRedirectAllowList if setRedirectAllowList is supplied', () => {
```

2023-08-01 17:05 UTC, JAdshead commented on __tests__/server/utils/onModuleLoad.spec.jsx
> +  it('calls setStateConfig with empty array if setRedirectAllowList is NOT supplied', () => {
```suggestion
  it('calls setRedirectAllowList with empty array if setRedirectAllowList is NOT supplied', () => {
```

2023-08-01 17:06 UTC, JAdshead commented on src/server/utils/onModuleLoad.js
> +      redirectAllowList,
```suggestion
      redirectAllowList = [],
```

2023-08-02 15:41 UTC, code-forger approved these changes

2023-08-02 17:26 UTC, JAdshead approved these changes

2023-08-02 18:24 UTC, merged