chore(workflows): use Node.js 18.x, same as the image
americanexpress/one-app pull request #1089
Opened 2023-08-14 20:25 UTC by PixnBits

## Description

continue #1067: use the same major version for the workflows

## Motivation and Context

increase test fidelity

## How Has This Been Tested?

most will be run as PR checks, the release process might need to be after

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

none, maybe confidence in tests

2023-08-14 20:44 UTC, JAdshead approved these changes

2023-08-14 22:22 UTC, PixnBits commented
consider #1090 for a longer-term improvement

2023-08-18 09:44 UTC, code-forger requested changes
is this superseded entirely by #1090 ?

2023-08-24 15:54 UTC, bishnubista approved these changes

2023-08-24 19:25 UTC, Matthew-Mallimo approved these changes

2023-08-31 20:31 UTC, JAdshead commented
closing for https://github.com/americanexpress/one-app/pull/1090

2023-08-31 20:31 UTC, closed without merging