feat(cache-module): implemented cached modules
americanexpress/one-app pull request #1094
Opened 2023-08-21 22:02 UTC by bishnubista

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2023-08-30 12:55 UTC, Matthew-Mallimo requested changes

2023-08-30 12:55 UTC, Matthew-Mallimo commented on src/server/utils/cacheCDNModules.js
> +  fs.stat(oneAppModuleCachePath, (error, stats) => {
```suggestion
  fs.stat(oneAppModuleCachePath, (error, stats) => {
```
Can we switch this to `async-await`

2023-09-06 14:11 UTC, Matthew-Mallimo approved these changes

2023-09-11 15:02 UTC, code-forger approved these changes

2023-09-11 20:20 UTC, merged