v5 - Upgrading to Node.js 20
americanexpress/one-app pull request #1321
Opened 2024-03-05 01:34 UTC by giulianok

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2024-03-11 05:19 UTC, 10xLaCroixDrinker requested changes

2024-03-11 05:19 UTC, 10xLaCroixDrinker commented on .github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml
> +        node-version: [20.x]
```suggestion
        node-version: [18.x, 20.x]
```

2024-03-11 16:30 UTC, JAdshead submitted a review, later dismissed

2024-03-11 16:37 UTC, Matthew-Mallimo submitted a review, later dismissed

2024-03-11 19:30 UTC, JAdshead approved these changes

2024-03-11 20:52 UTC, 10xLaCroixDrinker approved these changes

2024-03-12 14:34 UTC, Matthew-Mallimo approved these changes

2024-03-12 16:27 UTC, merged