feat(initclient): use serverState for hydration
americanexpress/one-app pull request #1323
Opened 2024-03-07 21:11 UTC by JAdshead

## Description

Use provide server state to improve hydration stability.

## Motivation and Context

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2024-03-07 21:12 UTC, JAdshead commented on package.json
> +    "holocron": "1.10.1",
this version includes a bug which allows us to provide redux and react-redux as peer deps.

2024-03-07 21:57 UTC, 10xLaCroixDrinker requested changes
please add tests or update existing assertions

2024-03-07 23:26 UTC, code-forger approved these changes

2024-03-11 15:56 UTC, Matthew-Mallimo approved these changes

2024-03-11 16:19 UTC, bishnubista approved these changes

2024-03-11 16:19 UTC, giulianok approved these changes
lgtm

2024-03-11 18:29 UTC, merged