feat(Dockerfile): use .nvmrc to build the image (5.x.x)
americanexpress/one-app pull request #1375
Opened 2024-04-11 00:01 UTC by PixnBits

## Description

use .nvmrc to build the image
and run workflows, creating a single point to define the Node.js version to use and thus making upgrades easier

## Motivation and Context

Avoid the myriad of locations where Node.js versions are recorded, i.e. Dockerfile and workflows. package.json engines will still need manual updates though (perhaps that can be a workflow, or a unit test to ensure it is satisfied by the contents of `.nvmrc`?)

## How Has This Been Tested?

built locally, though not run, but did see the expected label used when manually running `$ docker build . --build-arg VERSION=18.17.0` and `docker build . --build-arg VERSION=$(cat .nvmrc)`

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] These changes should be applied to a maintenance branch. (this is that PR, see #1090)
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

faster Node.js version updates? this is more for the maintainers so no impact to devs is the basic requirement 😅

2024-04-11 23:18 UTC, PixnBits commented
should we change https://github.com/americanexpress/one-app/blob/24dca2de9d97db021143500c868e078ea7b1eb6d/package.json#L6-L7 to include 16.x 
or https://github.com/americanexpress/one-app/blob/24dca2de9d97db021143500c868e078ea7b1eb6d/.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml#L13-L14 to remove 16.x ?

2024-04-12 18:07 UTC, 10xLaCroixDrinker commented
> should we change
> 
> https://github.com/americanexpress/one-app/blob/24dca2de9d97db021143500c868e078ea7b1eb6d/package.json#L6-L7
> 
> to include 16.x
> or
> https://github.com/americanexpress/one-app/blob/24dca2de9d97db021143500c868e078ea7b1eb6d/.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml#L13-L14
> 
> to remove 16.x ?

Remove 16

2024-04-13 15:10 UTC, 10xLaCroixDrinker requested changes

2024-04-13 15:10 UTC, 10xLaCroixDrinker commented on package.json
> +    "npm": "^9"
Your engines change is causing all workflows that run install to fail.

2024-04-15 07:26 UTC, code-forger approved these changes

2024-05-03 20:01 UTC, closed without merging