chore(workflow): update unit test workflow
americanexpress/one-app pull request #329
Opened 2020-10-01 17:57 UTC by JamesSingleton

Run Unit Tests on push to `main` and a pull request to `main`

## Description

Run the unit test workflow on pull requests to `main` as well as push to `main`

## Motivation and Context

So that we run the tests when we merge into `main`.

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2020-10-01 18:21 UTC, JAdshead requested changes

2020-10-01 18:21 UTC, JAdshead commented on .github/workflows/unit_test.yml
> +    branches:
could we still have them run on any PR ?

2020-10-02 12:14 UTC, infoxicator approved these changes

2020-10-02 15:07 UTC, nellyk approved these changes

2020-10-05 21:18 UTC, Francois-Esquire approved these changes

2020-10-06 15:21 UTC, merged