feat(dns): add option to enable app-level DNS caching
americanexpress/one-app pull request #727
Opened 2022-04-29 21:26 UTC by 10xLaCroixDrinker

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2022-04-29 21:54 UTC, bishnubista submitted a review, later dismissed

2022-05-02 16:24 UTC, Matthew-Mallimo commented on docs/api/modules/App-Configuration.md
> +The `dnsCache` option allows for enabling applcation-level DNS caching. It is disabled by default. When enabled, the dedault max TTL is `Infinity`.
```suggestion
The `dnsCache` option allows for enabling applcation-level DNS caching. It is disabled by default. When enabled, the default max TTL is `Infinity`.
```

2022-05-03 14:54 UTC, Matthew-Mallimo submitted a review, later dismissed

2022-05-03 21:01 UTC, JAdshead requested changes
just a little more info in docs

2022-05-04 16:26 UTC, JAdshead approved these changes

2022-05-04 17:05 UTC, bishnubista approved these changes

2022-05-04 17:24 UTC, merged