Feat: ExpressJS to Fastify migration
americanexpress/one-app pull request #878
Opened 2022-12-05 12:15 UTC by giulianok

feat: migrated express to fastify

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2022-12-06 15:08 UTC, bishnubista approved these changes

2022-12-06 18:29 UTC, giulianok commented
> **Size Change:** +8.13 kB (+1%)
> 
> **Total Size:** 689 kB
> 
> Filename	Size	Change	
> `./build/app/app.js`	173 kB	+7.5 kB (+5%)	🔍
> `./build/app/app~vendors.js`	387 kB	+512 B (0%)	
> `./build/app/service-worker-client.js`	7.26 kB	-3 B (0%)	
> `./build/app/vendors.js`	114 kB	+115 B (0%)	
> ℹ️ **View Unchanged**
> Filename	Size
> `./build/app/runtime.js`	7.07 kB
> [compressed-size-action](https://github.com/preactjs/compressed-size-action)

Just fyi, the bundles are identical, not sure why this diff is showing that, for example, app.js got an increased of 5%

## Fastify feature branch
<img width="1280" alt="Screen Shot 2022-12-06 at 1 28 36 PM" src="https://user-images.githubusercontent.com/8062245/205992482-acdae470-8559-4635-8d05-205a2e123d62.png">

## Report from `main` branch
<img width="1278" alt="Screen Shot 2022-12-06 at 1 12 29 PM" src="https://user-images.githubusercontent.com/8062245/205992603-444b3a18-0e00-44d0-b372-3e4fe84cb0a0.png">

2022-12-07 16:48 UTC, code-forger approved these changes

2022-12-07 17:23 UTC, bishnubista submitted a review, later dismissed

2022-12-07 18:26 UTC, 10xLaCroixDrinker requested changes
Hold on merging for discussion on testing

2023-01-25 16:12 UTC, 10xLaCroixDrinker requested changes

2023-01-25 16:12 UTC, 10xLaCroixDrinker commented on __tests__/server/plugins/reactHtml/createRequestHtmlFragment.spec.jsx
> +        // history: browserHistory,
```suggestion
```

2023-01-25 16:22 UTC, giulianok commented on package.json
> +    "node-fetch": "^2.6.7",
`node-fetch` was added in this PR https://github.com/americanexpress/one-app/pull/882/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519. @dogpatch626 do you know if we need it installed and that particular version?

2023-01-25 16:24 UTC, dogpatch626 commented on package.json
> +    "node-fetch": "^2.6.7",
yea we use that particular version in multiple repos for testing in particular I believe. installing it was just to replace got with node-fetch.

2023-01-25 16:26 UTC, giulianok commented on package.json
> +    "express": "^4.18.2",
right, completely forgot, those are left overs, we do not need them anymore. Also found some others that I just removed

2023-01-25 16:30 UTC, 10xLaCroixDrinker submitted a review, later dismissed

2023-01-25 17:50 UTC, Matthew-Mallimo commented on __tests__/server/plugins/addFrameOptionsHeader.spec.js
> +  test('does not add frame options header', () => {
in the `addCacheHeaders.spec.js` test file we use `it`, and here we are using `test`. We should be consistent

2023-01-26 18:22 UTC, Matthew-Mallimo approved these changes

2023-01-30 16:10 UTC, dogpatch626 approved these changes

2023-01-30 20:57 UTC, bishnubista approved these changes

2023-01-31 15:11 UTC, Matthew-Mallimo approved these changes

2023-01-31 20:23 UTC, 10xLaCroixDrinker approved these changes

2023-01-31 20:24 UTC, merged