[Fix] Matching headers with ExpressJS implementation
americanexpress/one-app pull request #897
Opened 2023-01-17 23:49 UTC by giulianok

Minor changes to headers to match current production implementation

## Description

Helmet overrides some of the headers added on the ExpressJS implementation which doesn't happen on Fastify since headers injected by Fastify take priority over the headers set to the raw response object by fastify helmet.

## Motivation and Context

Align with current headers' values

## How Has This Been Tested?

Manual tested different routes from expressjs implementation (production) and fastify implementation

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

2023-01-18 15:08 UTC, dogpatch626 approved these changes

2023-01-18 15:10 UTC, Matthew-Mallimo requested changes
Shouldn't have changes to the package lock

2023-01-18 16:00 UTC, giulianok commented
> Shouldn't have changes to the package lock

I needed to rebuild it because of conflicts, probably from the dev holocron cdn PR

2023-01-18 16:24 UTC, 10xLaCroixDrinker commented
> > Shouldn't have changes to the package lock
> 
> I needed to rebuild it because of conflicts, probably from the dev holocron cdn PR

There shouldn't be any conflicts with it in this branch because this branch should not have any changes to it. Please revert lockfile changes. They also increased the bundle size

2023-01-19 14:57 UTC, Matthew-Mallimo approved these changes

2023-01-19 15:47 UTC, merged